version: "3.8"

networks:
  traefikpublic:
    name: traefikpublic
    external: true

services:
  dboro:
    image: dboro.co.uk:latest
    networks:
      - traefikpublic
    deploy:
      placement:
        constraints:
          - node.hostname == moorie
      labels:
        traefik.enable: "true"
        traefik.http.routers.dboro.rule: "Host(`dboro.co.uk`)"
        traefik.http.routers.dboro.entrypoints: "websecure"
        traefik.http.routers.dboro.tls: "true"
        traefik.http.routers.dboro.tls.certresolver: "leresolver"
        traefik.http.routers.dboro.service: "dboro"
        traefik.http.services.dboro.loadbalancer.server.port: "80"