version: "3.8"

networks:
  traefikpublic:
    name: traefikpublic
    external: true

services:
  dboro:
    image: registry.dboro.co.uk/dboro.co.uk
    networks:
      - traefikpublic
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOMECLUSTER_VPS_HOSTNAME}
      labels:
        traefik.enable: "true"
        traefik.http.routers.dboro.rule: "Host(`${WEBSITE_URL}`)"
        traefik.http.routers.dboro.entrypoints: "websecure"
        traefik.http.routers.dboro.tls: "true"
        traefik.http.routers.dboro.tls.certresolver: "leresolver"
        traefik.http.routers.dboro.service: "dboro"
        traefik.http.services.dboro.loadbalancer.server.port: "80"